### PR TITLE
Tmm

### LINKED ISSUE #17: Migrate TMM
Needs a little bit of cleanup. 

* Bootstrap styles are trashing the header and footer
* Background image is wonky
* Modal backdrop is wonkedAF
* Correct the date on the post

### PR DESCRIPTION
**Pull request by shamshirz**
resolves #17 

## Updated 3/11

RE: Sam's issue with the game itself. I'm prepared to take it as it is and release. It's annoying the casino thing etc, but I don't really want to dive into the sauce again. thoughts?

[Re-deployed](https://sylver-studios-pr-16.herokuapp.com/games/2019/03/01/tmm.html)
#Working!
Very annoying Heroku routing vs. naming with spacing.
NEVER GOING TO NAME FILES WITH SPACES AGAIN. WHY DID I THINK THAT WAS THE RIGHT THING TO DO???
ImagesFixed

## Update 3/11

[Deployed](https://sylver-studios-pr-16.herokuapp.com/games/2019/03/01/tmm.html)
Working on image failures

## Original

Needs a few more tweaks. I cleaned it up in a kind of evil way by just copying the CSS and then tearing it up manually 😬

### CODE REVIEW

**Comment by samgqroberts** [comment]
some of the assets aren't loading:
image

**Comment by samgqroberts** [comment]
also created these issues, which I believe are more about the base game, not about the port to the blog:
https://github.com/SylverStudios/trump-money-maker/issues/26
https://github.com/SylverStudios/trump-money-maker/issues/25

**Comment by samgqroberts** [comment]
Trump ISS asset is missing too:
image

**Comment by rjdellecese** [comment]
Barring Sam's comments, this looks great!!! Nice work! Truly (y)our masterpiece...

**Comment by shamshirz** [comment]
This guy is 🔥 _hot_ 🔥  and going out. I'm going to hold off on the social media posting until the article goes up along with it. Finna catch the gasps with the "this is a PARODY" nature of the game before we have a riot on our hands

**Pull request merged**
