### PR TITLE
Add new favicon

### PR DESCRIPTION
**Pull request by rjdellecese**
Generated by favicon.io

Generation link: https://favicon.io/favicon-generator/?t=Ag&ff=Oxygen&fs=90&fc=%23222&b=rounded&bc=%23C0C0C0

Font: Oxygen
Text size: 90
Background color: #C0C0C0
Text color: #222

### CODE REVIEW

**Comment by samgqroberts** [comment]
Warning Warning this commit has also squashed #29 in too -- we shouldn't merge this til we're happy with #29

**Comment by samgqroberts** [comment]
also i leave the stylistic choices to aaron... unsure what the implications of having dark silver on light silver rather than white silver on medium silver are

**Comment by samgqroberts** [comment]
should we align these colors with the silver bar icon we have elsewhere?

**Comment by rjdellecese** [comment]
Ooops thank you for spotting that! Branched off the wrong base, apparently. Amended and force-pushed to fix.

**Review by shamshirz — APPROVED** [review]
**I'm good with this.** I think in the future we can do another pass. The bottom line is our favicon is low rez and doesn't look amazing, this one is an improvement for sure.

Personally, I'm a fan of ⚪️, possibly on a transparent background, but that's a story for a bigger SylverStudios. 👍 🚀Comparing ours & Goodreads, to Google, ElixirForum, and Git, which group do you want to fit into?
favicons

**Comment by rjdellecese** [comment]
Great point, but in the spirit of incremental improvements and the virtues of confused branding, merging in the meantime!

**Pull request merged**
